### PR TITLE
Preserve location of lexbuf

### LINKED ISSUE #19: Fix location on lexbuf
E.g.:

```
let x y =
  match%sedlex lexbuf with _ -> assert false
```

produces this error:

```
File "_none_", line 1:
Error: Unbound value lexbuf
```

which is not very helpful.

### PR DESCRIPTION
**Pull request by hhugo**
fix #19 

before
```
$ dune build
File "_none_", line 1:                
Error: This expression has type int but an expression was expected of type
         Sedlexing.lexbuf
```

after 
```
$ dune build
File "examples/repeat.ml", line 4, characters 15-17:
4 |   match%sedlex rr with
                   ^^
Error: This expression has type int but an expression was expected of type
         Sedlexing.lexbuf
```

### CODE REVIEW

File: src/syntax/ppx_sedlex.ml [hunk 1]
```diff
@@ -211,22 +211,26 @@ let gen_state lexbuf auto i (trans, final) =
...
-            ~rhs:[%expr Sedlexing.backtrack [%e evar ~loc lexbuf]];
+            ~rhs:[%expr Sedlexing.backtrack [%e lexbuf]];
         ])
   in
   let ret body =
+    let lhs =
+      match lexbuf with
+        | { pexp_desc = Pexp_ident { txt = Lident ident; _ }; pexp_loc } ->
+            pvar ~loc:pexp_loc ident
+        | _ -> assert false
```
Comment (smuenzel) [inline src/syntax/ppx_sedlex.ml:228]: You could use the `Longident.t loc` for the location (and get it from `method! expression` as before).
That way you avoid the `assert false`

Comment (hhugo) [reply src/syntax/ppx_sedlex.ml:228]: I still need the string inside the simple `ident` to construct the pattern

Comment (smuenzel) [reply src/syntax/ppx_sedlex.ml:228]: What about https://github.com/hhugo/sedlex/compare/fixloc...smuenzel:sedlex:fixloc-explore ?
Shorter and we encode our invariants in the type system, rather than in `assert false`

**Comment by smuenzel** [comment]
Other than the small comment I think this is good to go.

**Review by smuenzel — APPROVED** [review]

File: src/syntax/ppx_sedlex.ml (hunk 1 above)
Comment (hhugo) [reply src/syntax/ppx_sedlex.ml]: looks good, I've cherry-pick you commit

**Comment by hhugo** [comment]
@toots, this one looks ready for a merge, whenever you have time.

**Comment by toots** [comment]
Looks great, thank you.
